name: Test (alternative) Install Methods

on: push

jobs:
  install:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: INSTALL SCRIPT + cmake
      run: |
        wget $(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep 'browser_' | cut -d\" -f4 | grep -i install.sh)
        chmod +x install.sh
        ./install.sh --download wget --build cmake
        rm -rf *

    - name: Checkout
      run: |
        git clone https://github.com/$GITHUB_REPOSITORY ./

    - name: Setup FPM with GH Action
      if: ${{ !env.ACT }}
      uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup FPM without GH Action
      if: ${{ env.ACT }}
      run: |
        wget $(curl -s https://api.github.com/repos/fortran-lang/fpm/releases/latest | grep 'browser_' | cut -d\" -f4 | grep -i linux | grep -vi sha256) -O fpm
        chmod +x fpm

    - name: FPM
      run: |
        export PATH=".:$PATH"
        fpm build --profile release
